$ErrorActionPreference = "Stop"
$utf8 = New-Object System.Text.UTF8Encoding($false)
$root = (Get-Location).Path
$htmlPath = Get-ChildItem -LiteralPath $root -Directory | ForEach-Object { Get-ChildItem -LiteralPath $_.FullName -Filter "frontend_dashboard_v3.server.html" -File -ErrorAction SilentlyContinue } | Select-Object -First 1 -ExpandProperty FullName
if (-not $htmlPath) { throw "direct frontend html not found" }
$html = [IO.File]::ReadAllText($htmlPath, [Text.Encoding]::UTF8)
$start = $html.IndexOf("    function BFControlAdviceCardV2", [StringComparison]::Ordinal)
$end = $html.IndexOf("    function BFRecommendationSummaryV2", $start, [StringComparison]::Ordinal)
if ($start -lt 0 -or $end -lt 0) { throw "control card boundaries missing" }
$newBlock = @'
    function bfGuidanceRpcV3(payload) {
      return new Promise((resolve, reject) => {
        const socket = new WebSocket(WS_URL), timer = window.setTimeout(() => { try { socket.close() } catch (_) {} reject(new Error('指导保存超时')) }, 15000);
        socket.onopen = () => socket.send(JSON.stringify(payload));
        socket.onmessage = event => { let msg; try { msg = JSON.parse(event.data) } catch (_) { return } if (msg.type === 'foreman_guidance_saved' && msg.request_id === payload.request_id) { window.clearTimeout(timer); try { socket.close() } catch (_) {} resolve(msg) } if (msg.type === 'foreman_guidance_error' && msg.request_id === payload.request_id) { window.clearTimeout(timer); try { socket.close() } catch (_) {} reject(new Error(msg.message || '指导保存被拒绝')) } };
        socket.onerror = () => { window.clearTimeout(timer); try { socket.close() } catch (_) {} reject(new Error('8768指导保存通道不可用')) };
      });
    }
    function BFControlAdviceCardV2({ control, actions, contractReady }) {
      const action = bfPreferredControlActionV2(actions, control.id), [editing, setEditing] = useState(false), [saveState, setSaveState] = useState('idle'), [error, setError] = useState(''), [savedTarget, setSavedTarget] = useState(null);
      const status = action?.status || (contractReady ? 'eligible' : 'needs_data'), current = bfFiniteControlNumberV3(action?.current_value), computedTarget = bfFiniteControlNumberV3(action?.recommended_target), target = savedTarget ?? computedTarget, change = current != null && target != null ? target - current : bfFiniteControlNumberV3(action?.recommended_change), hasTarget = current != null && target != null && change != null, isHold = contractReady && !action, guidanceSaved = savedTarget != null, statusLabel = isHold ? '保持不动' : BF_ACTION_STATUS_LABELS[status] || status, direction = hasTarget ? (change > 0 ? '增加' : change < 0 ? '减少' : '保持') : '';
      const displayTarget = target != null ? target : current, pressureAction = bfPreferredControlActionV2(actions, 'P_blast_cold'), pciAction = bfPreferredControlActionV2(actions, 'PCI_set'), max = control.id === 'P_blast_cold' ? Number(action?.limit_snapshot?.normal_q3 ?? action?.limit_snapshot?.hard_max ?? Infinity) : 45;
      useEffect(() => { if (!editing && displayTarget != null) setSavedTarget(current => current) }, [editing, displayTarget]);
      const saveManual = async event => { event.preventDefault(); const numeric = Number(event.currentTarget.elements.namedItem('guidance_target')?.value), min = control.id === 'P_blast_cold' ? 400 : 0; if (!Number.isFinite(numeric) || numeric < min || numeric > max) { setError(control.id === 'P_blast_cold' ? '冷风压力必须不低于400 kPa且不超过动态Q3' : '喷煤设定必须在0～45 t/h内'); return } const otherId = control.id === 'P_blast_cold' ? 'PCI_set' : 'P_blast_cold', otherAction = otherId === 'P_blast_cold' ? pressureAction : pciAction, otherTarget = bfFiniteControlNumberV3(otherAction?.recommended_target) ?? bfFiniteControlNumberV3(otherAction?.current_value); setSaveState('saving'); setError(''); try { await bfGuidanceRpcV3({ type: 'foreman_guidance_save', request_id: 'guidance_' + Date.now(), furnace_id: 'GL02', diagnosis_ts: action?.effective_at || new Date().toISOString(), current: { P_blast_cold: bfFiniteControlNumberV3(pressureAction?.current_value), PCI_set: bfFiniteControlNumberV3(pciAction?.current_value) }, computed: { P_blast_cold: bfFiniteControlNumberV3(pressureAction?.recommended_target) ?? bfFiniteControlNumberV3(pressureAction?.current_value), PCI_set: bfFiniteControlNumberV3(pciAction?.recommended_target) ?? bfFiniteControlNumberV3(pciAction?.current_value) }, guidance: { [control.id]: numeric, [otherId]: otherTarget }, limits: { P_blast_cold: pressureAction?.limit_snapshot || {}, PCI_set: pciAction?.limit_snapshot || {} }, cold_pressure_effective_at: pressureAction?.effective_at || null, pci_effective_at: pciAction?.effective_at || null, operator_note: '页面手动指导' }); setSavedTarget(numeric); setEditing(false); setSaveState('saved') } catch (e) { setSaveState('error'); setError(String(e?.message || e)) } };
      const mainText = hasTarget ? '当前 ' + fmtNum(current, 1) + ' → ' + (guidanceSaved ? '工长指导 ' : '建议 ') + fmtNum(target, 1) : isHold ? '本炉况不调整该变量' : status === 'needs_data' ? '数据不足，不生成调整量' : status === 'blocked' ? '安全门禁已阻断调整' : '等待现场人工确认';
      let detail = '8768未返回完整建议合同'; if (hasTarget) detail = direction + ' ' + fmtNum(Math.abs(change), 1) + ' ' + (action?.unit || control.unit) + (guidanceSaved ? ' · 已采用工长指导值' : ' · 仅在合同可执行时显示计算目标'); else if (isHold) detail = '保持当前设定，继续按观察窗口监视'; else if (action?.blocking_reasons?.length) detail = action.blocking_reasons[0]; else if (action?.missing_inputs?.length) detail = '缺少：' + action.missing_inputs.map(bfAuditFieldName).join('、'); else if (action?.manual_confirmation_reasons?.length) detail = action.manual_confirmation_reasons[0];
      const clamped = !!action?.step_tier?.clamped, limitNote = clamped ? (control.id === 'P_blast_cold' ? '标准步长已受30天Q3或400 kPa硬下限限幅' : '标准步长已受10–45 t/h边界限幅') : action?.step_tier?.standard_step != null ? '标准步长 ' + action.step_tier.standard_step + ' ' + (action.unit || control.unit) : '无调整步长', effective = action?.effective_at ? (control.id === 'PCI_set' && action.adjustment_direction !== 'stop' ? '下个整点生效：' + action.effective_at : '建议确认时刻：' + action.effective_at) : '当前不生成生效时刻', boundary = status === 'blocked' ? '已阻断，禁止执行' : status === 'needs_data' ? '禁止前端替代生成' : '任何修改均需值班工长批准';
      const editor = editing ? <form className="bf-guidance-editor-v3" onSubmit={saveManual}><label><span>指导目标（{control.unit}）</span><input name="guidance_target" type="number" step={control.id === 'P_blast_cold' ? '0.1' : '1'} min={control.id === 'P_blast_cold' ? '400' : '0'} max={Number.isFinite(max) ? String(max) : undefined} defaultValue={displayTarget != null ? displayTarget : ''} autoFocus /></label><div><button type="submit" disabled={saveState === 'saving'}>{saveState === 'saving' ? '保存中…' : '保存并确认指导'}</button><button type="button" onClick={() => { setEditing(false); setError('') }}>取消</button></div>{error && <small className="bf-guidance-error-v3">{error}</small>}<small>只保存指导并写入审计，不向设备下发控制指令。</small></form> : <button type="button" className="bf-guidance-edit-v3" onClick={() => { setEditing(true); setError('') }}>修改并保存工长指导</button>;
      return <article className={'bf-control-advice-card-v2 bf-control-advice-card-v3 ' + (control.id === 'P_blast_cold' ? 'pressure' : 'pci') + ' status-' + status} data-control-variable={control.id}><header><div><span>工长可调变量</span><h2>{control.label}</h2></div><b>{guidanceSaved ? '工长指导已保存' : statusLabel}</b></header><div className="bf-control-advice-main-v2 bf-control-advice-main-v3"><strong>{mainText}</strong><span>{action?.unit || control.unit}</span></div><p>{detail}</p><footer><span>{limitNote}</span><span>{effective}</span></footer>{editor}<small>只读建议 · {boundary} · 修改仅写入指导审计</small></article>;
    }
'@
$newBlock = $newBlock.Replace("@@BT@@", ([char]96).ToString())
$html = $html.Substring(0, $start) + $newBlock + $html.Substring($end)
$styleMarker = "    /* REQ-8093-CORE-SPARK-DETAIL-CORRELATION-20260715 */"
$styleBlock = @'
    ; (function () { const id = 'req-foreman-guidance-inputs-20260807'; if (document.getElementById(id)) return; const el = document.createElement('style'); el.id = id; el.textContent = @@BT@@.bf-control-advice-card-v3{min-height:220px!important;padding:16px 18px!important;gap:10px!important}.bf-control-advice-card-v3.pressure{border-color:rgba(255,177,71,.8)!important;border-left-color:#ffb347!important;background:linear-gradient(135deg,rgba(91,53,15,.92),rgba(12,32,47,.96))}.bf-control-advice-card-v3.pci{border-color:rgba(63,214,173,.78)!important;border-left-color:#3fd6ad!important;background:linear-gradient(135deg,rgba(10,75,67,.92),rgba(7,31,48,.96))}.bf-control-advice-main-v3 strong{font-size:34px!important;color:#ffe0a5!important}.bf-control-advice-card-v3.pci .bf-control-advice-main-v3 strong{color:#a6f4df!important}.bf-guidance-edit-v3{min-height:34px;padding:7px 10px;border:1px solid #f4b44e;border-radius:4px;color:#fff2cb;background:rgba(122,78,17,.58);font-family:SimSun,"宋体",serif;font-weight:700;cursor:pointer}.pci .bf-guidance-edit-v3{border-color:#44d7b0;color:#b8f7e7;background:rgba(10,105,84,.48)}.bf-guidance-editor-v3{display:grid;gap:7px;padding:9px;border:1px solid rgba(255,213,143,.46);background:rgba(4,22,36,.78)}.bf-guidance-editor-v3 label{display:grid;grid-template-columns:145px minmax(0,1fr);align-items:center;gap:8px;color:#e9f3f8;font-size:12px}.bf-guidance-editor-v3 input{min-width:0;min-height:30px;padding:4px 7px;border:1px solid #5785a1;border-radius:3px;color:#f4fbff;background:#071d30;font-family:Consolas,SimSun,"宋体",serif}.bf-guidance-editor-v3>div{display:flex;gap:7px}.bf-guidance-editor-v3 button{min-height:30px;padding:5px 9px;border:1px solid #51c693;border-radius:3px;color:#effff7;background:#155b4b;font-family:SimSun,"宋体",serif;cursor:pointer}.bf-guidance-editor-v3 button[type=button]{border-color:#60839b;background:#17384b}.bf-guidance-error-v3{color:#ff9d9d!important}@media(max-width:767px){.bf-control-advice-main-v3 strong{font-size:27px!important}.bf-guidance-editor-v3 label{grid-template-columns:1fr}}@@BT@@; document.head.appendChild(el) })();
'@
$styleBlock = $styleBlock.Replace("@@BT@@", ([char]96).ToString())
if ($html.IndexOf("req-foreman-guidance-inputs-20260807", [StringComparison]::Ordinal) -lt 0) { $html = $html.Replace($styleMarker, $styleBlock + [Environment]::NewLine + $styleMarker) }
[IO.File]::WriteAllText($htmlPath, $html, $utf8)
Write-Output $htmlPath
