from __future__ import annotations

import argparse
import pprint
from pathlib import Path

from build_abc33_handbook64_revision import CHAPTERS, REQ_ID, RULES


GUIDANCE_VERSION = "abc33-handbook64-guidance.v1.20260810"


def build_guidance() -> dict[str, dict[str, object]]:
    return {
        str(rule["id"]): {
            "formation_principle": str(rule["mechanism"]),
            "intervention_steps": tuple(str(step) for step in rule["steps"]),
            "source_refs": tuple(
                f"见习高炉长手册·第{chapter_id}章《{CHAPTERS[int(chapter_id)]}》"
                for chapter_id in rule["chapters"]
            ),
        }
        for rule in RULES
    }


def render_module() -> str:
    guidance = build_guidance()
    if len(guidance) != 33:
        raise RuntimeError(f"Expected 33 guidance entries, got {len(guidance)}")
    lines = [
        '"""Generated production-safe formation principles and intervention flows for ABC33.',
        "",
        "This file contains process-level handbook guidance only. It deliberately",
        "contains no scoring formula, weight, exact threshold or normalized feature.",
        f"Generated by tools/export_abc_rule_guidance.py for {REQ_ID}.",
        '"""',
        "from __future__ import annotations",
        "",
        f'GUIDANCE_VERSION = "{GUIDANCE_VERSION}"',
        f'REQUIREMENT_ID = "{REQ_ID}"',
        "RULE_GUIDANCE: dict[str, dict[str, object]] = "
        + pprint.pformat(guidance, width=120, sort_dicts=False),
        "",
        "EXPECTED_RULE_IDS = tuple(",
        "    [f\"A{i}\" for i in range(1, 10)]",
        "    + [f\"B{i}\" for i in range(1, 14)]",
        "    + [f\"C{i}\" for i in range(1, 12)]",
        ")",
        "if tuple(RULE_GUIDANCE) != EXPECTED_RULE_IDS:",
        "    raise RuntimeError(\"ABC33 guidance must contain A1-A9/B1-B13/C1-C11 in order\")",
        "if any(len(tuple(item.get(\"intervention_steps\") or ())) != 5 for item in RULE_GUIDANCE.values()):",
        "    raise RuntimeError(\"Every ABC33 guidance entry must contain exactly five intervention steps\")",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Export handbook64 guidance into the ABC33 runtime module.")
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_module(), encoding="utf-8")
    print(f"wrote={args.output} rules=33 version={GUIDANCE_VERSION}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
